language: python
python: 3.5
sudo: false

branches:
    only:
        - master
        - /^\d\.\d+$/

env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py35

install:
    - pip install -U tox codecov

script: tox

after_success:
    - codecov

cache:
    directories:
        - $HOME/.cache/pip
